DesignationTest/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace DesignationTest.Models
{
    public class AppDbContext : DbContext
    {

        public AppDbContext() { }

        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

       
        public DbSet<Designation> Designations { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=DesignationDB;Trusted_Connection=True;");
        }

    }
}

DesignationTest/Models/Designation.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DesignationTest.Models
{
    public class Designation
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string DesignationId { get; set; }

        [Required, StringLength(30)]
        public string DesignationName { get; set; } = string.Empty;
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreateDate { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime ModifiedDate { get; set; }
    }
}

DesignationTest/Models/ErrorViewModel.cs
namespace DesignationTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesignationTest/Controllers/DesignationController.cs
using DesignationTest.Models;
using DesignationTest.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DesignationTest.Controllers
{
    public class DesignationController : Controller
    {
        private readonly AppDbContext _db;

        public DesignationController(AppDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index(int? id)
        {
            
            VmDesignation Emp = new VmDesignation();

            var oEm = _db.Designations.Where(x => x.Id == id).FirstOrDefault();
            if (oEm != null)
            {
                Emp.Id = oEm.Id;
                Emp.DesignationId = oEm.DesignationId;
                Emp.DesignationName = oEm.DesignationName;
                Emp.CreateDate = oEm.CreateDate;
                Emp.ModifiedDate = oEm.ModifiedDate;

            }

            Emp = Emp == null ? new VmDesignation() : Emp;
           // Emp.DesignationId += _db.Designations.Max(x => x.DesignationId);
            //Emp.DesignationId = oEm.DesignationId;
            ViewData["EmployeeList"] = _db.Designations.ToList();
            return View(Emp);

        }

        [HttpPost]
        public async Task<IActionResult> Index(VmDesignation vmEmp)
        {

            var oEmployee = _db.Designations.FirstOrDefault(x => x.Id == vmEmp.Id);
            if (oEmployee == null)
            {
                oEmployee = new Designation();
                //oEmployee.ID = "GCTL-00" + vmEmp.ID;
                oEmployee.DesignationName = vmEmp.DesignationName;
                oEmployee.DesignationId = vmEmp.DesignationId;
                oEmployee.CreateDate = vmEmp.CreateDate;
                _db.Designations.Add(oEmployee);
            }
            else
            {
                oEmployee = new Designation();
                oEmployee.DesignationName = vmEmp.DesignationName;
                oEmployee.DesignationId = vmEmp.DesignationId;
                oEmployee.CreateDate = vmEmp.CreateDate;
                oEmployee.DesignationId = vmEmp.DesignationId;
            }

            await _db.SaveChangesAsync();
            return RedirectToAction("Index", new { resetId = true });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var emp = _db.Designations.Find(id);
            _db.Designations.Remove(emp);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DesignationTest/Controllers/HomeController.cs
using DesignationTest.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DesignationTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesignationTest/Views/Designation/Index.cshtml
@model DesignationTest.ViewModel.VmDesignation
@{
    ViewData["Title"] = "Index";
    var BV = Model.Id > 0 ? "Update" : "Add";
    var listEmployee = ViewData["EmployeeList"] as List<DesignationTest.Models.Designation>;
}

<form id="form" asp-controller="Designation" asp-action="Index" method="post">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="DesignationId">ID</label>
                    <input type="text" class="form-control" asp-for="DesignationId" placeholder="Enter ID"  />
                    <span asp-validation-for="DesignationId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="DesignationName">Emp Name</label>
                    <input type="text" class="form-control" asp-for="DesignationName" placeholder="Enter Name" />
                    <span asp-validation-for="DesignationName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CreateDate">Create Date</label>
                    <input type="datetime-local" class="form-control" asp-for="CreateDate" />
                    <span asp-validation-for="CreateDate" class="text-danger"></span>
                </div>
                <div class="form-group mx-0">
                 
                   
                    <label asp-for="ModifiedDate">Last Update</label>
                    <input type="datetime-local" class="form-control" asp-for="ModifiedDate" />
                    <span asp-validation-for="ModifiedDate" class="text-danger"></span>
                
                </div>
                <h>Create Date</h>
                <div>@Model.CreateDate</div>
            </div>
          
            <div class="col-6">
                <div class="form-group my-6">
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <h>Modified Date</h>
                    <div>@Model.ModifiedDate</div>
                </div>
             </div>
            <div>
                <button type="submit" class="btn btn-primary">@BV</button>
                <a asp-action="Index" class="btn btn-primary">Reset</a>
            </div>
        </div>
    </div>

</form>

<br />
<br />
<h1 style="text-align:center">Employee Table</h1>

<div class="container">
    <table class="table table-bordered table-active">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Create</th>
                <th>Modified Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in listEmployee)
            {
                <tr>
                    <td>@item.DesignationId</td>
                    <td>@item.DesignationName.ToUpper()</td>
                    <td>@item.CreateDate</td>
                    <td>@item.ModifiedDate</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Index" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DesignationTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DesignationTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignationTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesignationTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignationTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DesignationTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>